spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_tidy_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC #数据库连接地址
    username: root #用户名
    password: 123456 #密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动类
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  servlet:
    multipart:
      max-file-size: 100MB #最大上传文件大小
      max-request-size: 100MB #最大请求大小

server:
  port: 8080  # 端口号
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
#    map-underscore-to-camel-case: true #驼峰命名规则

pagehelper:
  helper-dialect: mysql #设置数据库类型
  auto-dialect: true #自动识别数据库类型
  reasonable: true #分页合理化
  support-methods-arguments: true #支持方法参数

qcloud:
  cos:
    endpoint: https://file-tidy-1328756109.cos.ap-beijing.myqcloud.com
    bucketName: file-tidy-1328756109

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  # 配置
  configuration:
    # 驼峰式命名
    map-underscore-to-camel-case: true
    # 全局映射器启用缓存
    cache-enabled: true
    # 指定 MyBatis 所用日志的具体实现
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    # 配置默认的执行器
    default-executor-type: reuse
    # 允许 JDBC 支持自动生成主键
    use-generated-keys: true